"""Phase 2: the correlation energy outside the valence active space, variationally.

The vignette computes NEVPT2 on CASSCF(10e,8o), which is a *perturbative*
estimate of the correlation lying outside that space. This script scores that
estimate against a variational measurement of the same quantity, obtained by
DMRG in an active space no exact diagonalisation here can reach.

Three energies, and the distinction between them is the whole point:

``CAS(10e,26o)``
    Every orbital except the two frozen N 1s cores. This *is* frozen-core FCI in
    cc-pVDZ -- 4.3e9 determinants -- and ``E_DMRG(26o) - E_CASSCF(8o)`` is the
    correlation energy the valence active space misses, measured rather than
    estimated.
``CAS(14e,28o)``
    Every orbital and every electron: full CI in cc-pVDZ, 1.4e12 determinants.
    This exists because PySCF's NEVPT2 excites out of the CASSCF core, so the
    vignette's NEVPT2 energy *contains* core correlation. Scoring it against the
    frozen-core number would compare two different quantities, and the mismatch
    (3.9 mHa at 1.098 A by frozen-core against all-electron CCSD(T)) dwarfs any
    agreement worth reporting.
``CAS(10e,20o)``
    An intermediate rung, carried so the approach to the complete space is
    visible rather than assumed.

**There is no exact reference at any of these rungs.** Nothing here is reported
as an error against a known answer. DMRG is variational, so the lowest energy
found at a rung is the best upper bound available, and the uncertainty on it is
built from what actually varies: the last step in the chi sweep, the
disagreement between the two orbital orderings, and the seed spread. The
ordering disagreement carries the most weight, because it is the only signal
that caught the local-minimum failure Phase 1 exposed.

    uv run python scripts/n2_outside_correlation.py
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any

from tn_quantum_chemistry.n2_ladder import RUNG_MEANING, load_ladder, summarise_rung
from tn_quantum_chemistry.schema import RecordStore, Status

HARTREE_TO_KCAL = 627.509474063

#: Phase 2 writes one store per geometry, so the ladder is spread over several
#: files and the default has to find all of them. It used to name only the Phase
#: 1 store, which meant the command recorded in ``README.md`` produced a table
#: with every DMRG column empty -- the committed CSV had been generated by an
#: invocation that listed the stores by hand.
#:
#: ``external_check_*`` is deliberately not matched. It holds the ladder run at a
#: *published* geometry (see ``scripts/n2_external_check.py``), where no vignette
#: CASSCF or NEVPT2 exists, so including it would add a row this table cannot
#: fill in.
LADDER_STORE_GLOBS = (
    "data/raw/n2_ladder/n2_active_space_ladder.jsonl",
    "data/raw/n2_ladder/phase2_*/n2_active_space_ladder.jsonl",
)


def default_ladder_stores() -> list[Path]:
    """Every Phase 1 and Phase 2 store, in a stable order."""
    root = Path()
    found: list[Path] = []
    for pattern in LADDER_STORE_GLOBS:
        found.extend(sorted(root.glob(pattern)))
    return found


def load_vignette(path: Path) -> dict[tuple[float, str], float]:
    """Vignette energies keyed by (bond length, method), cc-pVDZ only."""
    energies: dict[tuple[float, str], float] = {}
    for record in RecordStore(path):
        if record.basis != "cc-pvdz" or record.status != Status.CONVERGED:
            continue
        key = (round(record.geometry_parameters["bond_length"], 6), record.method)
        energies[key] = record.e_total
    return energies


def fmt(value: float | None, spec: str = ".6f") -> str:
    return "—" if value is None else format(value, spec)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ladder", type=Path, nargs="+",
                        default=default_ladder_stores(),
                        help="one or more record stores; defaults to every Phase 1 "
                             "and Phase 2 store (see LADDER_STORE_GLOBS)")
    parser.add_argument("--vignette", type=Path,
                        default=Path("data/raw/n2_vignette/n2_vignette.jsonl"))
    parser.add_argument("--out", type=Path, default=Path("figures/n2_outside_correlation.csv"))
    args = parser.parse_args(argv)

    ladder = load_ladder(args.ladder)
    vignette = load_vignette(args.vignette)
    bond_lengths = sorted({k[0] for k in ladder})

    rows = []
    for bond_length in bond_lengths:
        casscf = vignette.get((bond_length, "CASSCF(10e,8o)"))
        nevpt2 = vignette.get((bond_length, "NEVPT2/CASSCF(10e,8o)"))
        row: dict[str, Any] = {
            "bond_length_angstrom": bond_length,
            "e_casscf_8o": casscf,
            "e_nevpt2": nevpt2,
            "nevpt2_correction": None if None in (casscf, nevpt2) else nevpt2 - casscf,
        }
        for (n_elec, n_orb), meaning in RUNG_MEANING.items():
            summary = ladder.get((bond_length, n_elec, n_orb))
            prefix = f"{n_elec}e{n_orb}o"
            if summary is None:
                row[f"e_dmrg_{prefix}"] = None
                row[f"uncertainty_{prefix}"] = None
                continue
            stats = summarise_rung(summary)
            row[f"e_dmrg_{prefix}"] = stats["e_best"]
            row[f"uncertainty_{prefix}"] = stats["uncertainty"]
            row[f"ordering_gap_{prefix}"] = stats["ordering_gap"]
            row[f"chi_step_{prefix}"] = stats["chi_step"]
            row[f"seed_spread_{prefix}"] = stats["seed_spread"]
            row[f"sweep_drift_{prefix}"] = stats["sweep_drift"]
            row[f"sweeps_saturated_{prefix}"] = stats["sweeps_saturated_at_chi_max"]
            row[f"chi_max_{prefix}"] = stats["chi_max"]
            row[f"meaning_{prefix}"] = meaning

        # The variational answer to the question the vignette answered
        # perturbatively: how much correlation does CAS(10e,8o) miss?
        frozen_core_fci = row.get("e_dmrg_10e26o")
        if casscf is not None and frozen_core_fci is not None:
            row["outside_correlation_variational"] = frozen_core_fci - casscf

        # NEVPT2 is scored only against the all-electron rung, because it
        # carries core correlation and the frozen-core rung does not.
        full_ci = row.get("e_dmrg_14e28o")
        if nevpt2 is not None and full_ci is not None:
            row["nevpt2_error"] = nevpt2 - full_ci
            row["nevpt2_error_kcal"] = (nevpt2 - full_ci) * HARTREE_TO_KCAL
        rows.append(row)

    if not rows:
        print("no records found in", ", ".join(str(p) for p in args.ladder))
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with args.out.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print("### Variational energies (no exact reference exists at these rungs)\n")
    print("| R (Å) | rung | what it is | E_DMRG (Ha) | χ_max | ordering gap | "
          "sweep drift | uncertainty |")
    print("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for row in rows:
        for (n_elec, n_orb), meaning in RUNG_MEANING.items():
            prefix = f"{n_elec}e{n_orb}o"
            if row.get(f"e_dmrg_{prefix}") is None:
                continue
            print(
                f"| {row['bond_length_angstrom']:.3f} "
                f"| ({n_elec}e,{n_orb}o) | {meaning} "
                f"| {fmt(row[f'e_dmrg_{prefix}'], '.9f')} "
                f"| {row.get(f'chi_max_{prefix}', '—')} "
                f"| {fmt(row.get(f'ordering_gap_{prefix}'), '.2e')} "
                f"| {fmt(row.get(f'sweep_drift_{prefix}'), '.2e')} "
                f"| {fmt(row.get(f'uncertainty_{prefix}'), '.2e')} |"
            )

    print("\n### Correlation outside CAS(10e,8o): perturbative vs variational\n")
    print("| R (Å) | NEVPT2 correction | variational (26o − CASSCF) | "
          "NEVPT2 − full CI | kcal/mol |")
    print("| --- | --- | --- | --- | --- |")
    for row in rows:
        print(
            f"| {row['bond_length_angstrom']:.3f} "
            f"| {fmt(row['nevpt2_correction'])} "
            f"| {fmt(row.get('outside_correlation_variational'))} "
            f"| {fmt(row.get('nevpt2_error'))} "
            f"| {fmt(row.get('nevpt2_error_kcal'), '.2f')} |"
        )
    print("\nNEVPT2 is scored against CAS(14e,28o) only: it excites out of the "
          "CASSCF core, so the frozen-core rung is not the same quantity.")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
